#!/bin/bash

source common.sh

POST '{"extension":"tangleid","command":"revoke_claim","uuid": "SD9BCRDGJYWDHPTDNOPRULFWWG","txnhash":"NFVYYZEQHZYJHILHNDONAWSHSCSCEXXEFUQORWGCMCBDIOMZTUKGMOJWOIJNUKI9BIDWLBUGZKRXZ9999"}'
